language: php
sudo: false
dist: trusty

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
      pecl install pcov-1.0.0
    fi

install:
  - rm composer.lock
  - travis_retry composer -n update --prefer-dist

script:
  - vendor/bin/ecs check --config=ecs.yml .
  - |
    if [ "x$DOCKER_POSTGRES" == "xyes" ]; then
      sudo docker exec -ti postgres11 psql postgres -U postgres -c "CREATE DATABASE testing"
    else
      psql -c 'CREATE DATABASE testing;' -U postgres
    fi
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
       ./vendor/bin/phpunit --configuration phpunit.travis.xml --coverage-clover build/logs/clover.xml
    else
       ./vendor/bin/phpunit --configuration phpunit.travis.xml
    fi

after_success:
  - |
    if [ "x$COVERAGE" == "xyes" ]; then
      travis_retry vendor/bin/php-coveralls -v
    fi

matrix:
  fast_finish: true
  allow_failures:
    - php: "7.4"
  include:
    - stage: Test72PG11
      php: "7.2"
      env: DB=pgsql POSTGRESQL_VERSION=11.0
      sudo: required
      services:
        - docker
    - stage: Test73PG10
      php: "7.3"
      env: DB=pgsql POSTGRESQL_VERSION=10.0 COVERAGE=yes
      sudo: required
      services:
        - postgresql
      addons:
        postgresql: "9.6"
      before_script:
        - bash ./tests/travis/install-postgres-10.sh
    - stage: Test73PG11
      php: "7.3"
      env: DB=pgsql DOCKER_POSTGRES=yes POSTGRESQL_VERSION=11.0 COVERAGE=yes
      sudo: required
      services:
        - docker
        - postgresql
      addons:
        postgresql: "9.6"
      before_script:
        - bash ./tests/travis/install-postgres-11.sh
    - stage: Test74
      php: "7.4"
      env: DB=pgsql DOCKER_POSTGRES=yes POSTGRESQL_VERSION=11.0
      sudo: required
      services:
        - docker
        - postgresql
      before_script:
        - bash ./tests/travis/install-postgres-11.sh
